# Python notes 

In [1]:
print("Hello World")

Hello World


## Variable Types:

In [3]:
x = 1 
print(type(x))

<class 'int'>


In [2]:
x = 1.0
print(type(x))

<class 'float'>


In [4]:
x = 1+2j
print(type(x))

<class 'complex'>


In [7]:
x = "This is a string"
print(type(x))

<class 'str'>


## Converting between different variables

In [3]:
# Variables can be converted from one type to antothing using the following
# functions: 
# float(insert variable)
# int(insert variable)
# complex(instert variable)


In [6]:
x = 1
y = float(x)
print(y)
print(type(y))

1.0
<class 'float'>


## Input statements

In [3]:
x = input("Enter the value of x: ")
print("The value of x is",x)

Enter the value of x: 10
The value of x is 10


In [4]:
# Further variable conversion 
# Anything you type in is a string but we prefer to work with actual numbers :D
temp = input("Enter the value of x: ")
x = float(temp)
print("The value of x is",x)

Enter the value of x: 10
The value of x is 10.0


In [5]:
x = float(input("Enter the value of x: "))
print("The value of x is",x)

Enter the value of x: 10
The value of x is 10.0


## Basic Maths

In [1]:
# addition and subtraction
x = 1 
y = 2 
c = x + y 
print(c) 
d = x - y 
print(d)

3
-1


In [7]:
# multiplication and division
x = 1*1
y = 4/2
print(x)
print(y)

1
2.0


In [8]:
# floor division (division to the nearest integer)
x = 2.8//2
print(x)

1.0


In [6]:
# modulus (the remainder after a number is divided by another number)
x = 15%10
print(x)

5


In [10]:
# powers 
x=2**3
print(x)

8


## More Maths

In [7]:
# python modifiers

x += 1 # add 1 to x (i.e make x bigger by 1)

x -+ 4 # subtract 4 from x 

x *= -2.6 # multiply x by -2.6

x /= 5*y # divide x by 5 times y 

x //= 3.4 # divide by 3.4 and round down to an integer

2

### Example

In [1]:
# A ball dropped from a tower of height h. It has an intial velocity of zero 
# and accelerates downwards under gravity, write a program that asks the user to
# enter the height in meters of the tower and a time interval t in seconds, then 
# print on the screen the height of the ball above the ground at time t after it 
# is dropped, ingnoring air resistance

# s = 1/2gt^2 where g = 9.81 ms^-1

h = float(input("Enter the height of the tower: "))
t = float(input("Enter the time interval: "))
g = 9.81 #ms^-2
s = 1/2*g*t**2
print("The height of the ball is",h-s,"meters")

Enter the height of the tower: 100
Enter the time interval: 2
The height of the ball is 80.38 meters


## Packages? 

Python cannot perform certain mathematical functions such as calculating logarithm, multiplying matrices straight away. You need to first import a package to allow script to perform certain tasks. A package is just a collection of related useful things python can do that is not automatically imported. 

For instance, all the standard mathematical functions, such as logarithm and square root, are contained in a package called math. 

Before you can use any of these functions you have to tell the computer that you want to. For example, to tell the computer you want to use the log function, you would add the following line to your program:

In [2]:
from math import log

This tells the computer to “import” the logarithm function from the math package, which means that it copies the code defining the function from where it is stored (usually on the hard disk of your computer) into the computer’s memory, ready for use by your program.

You need to import each function you use only once per program: once the function has been imported it continues to be available until the program ends. You must import the function before the first time you use it in a calculation and it is good practice to put the “from” statement at the very start of the program, which guarantees that it occurs before the first use of the function and also makes it easy to find when you are working on your code.

In [5]:
#now look:

x = log(2.5)
print(x)

0.9162907318741551


In [ ]:
#The maths package has a lot of useful functions:

log #natural logarithm
log10 #log base 10
exp #exponential
sin, cos, tan #sine, cosine, tangent (argument in radians)
asin, acos, atan #arcsine, arccosine, arctangent (in radians)
sinh, cosh, tanh #hyperbolics sine, cosine and tangent
sqrt #positive square root

The math package also contains a number of less common functions, such as the Gaussian error function and the gamma function, as well as two objects that are not functions at all but constants, namely e and π, which are denoted e and pi. This program, for instance, calculates the value of π^2:

In [7]:
from math import pi
print(pi**2)

9.869604401089358


Import multiple functions like this:

In [8]:
from math import log,exp

Import all functions in a package like this:

In [7]:
from math import *

The * means "everything" here

Finally, some large packages are for convenience split into smaller subpackages, called modules. A module within a larger package is referred to as packagename.modulename. As we will see shortly, for example, there are a large number of useful mathematical facilities available in the package called numpy, including facilities for linear algebra and Fourier transforms, each in their own module within the larger package. Thus the linear algebra module is called numpy.linalg and the Fourier transform module is called numpy.fft (for “fast Fourier transform”). We can import a function from a module thus:


In [10]:
from numpy.linalg import inv

This calculates the inverse of a matrix. 

Small packages like math have no submodules.

### Example: 2.2

Suppose the position of a point in two-dimensional space is given to us in polar
coordinates r, θ and we want to convert it to Cartesian coordinates x, y. How
would we write a program to do this?

In [11]:
from math import sin,cos,pi
r = float(input("Enter r: "))
d = float(input("Enter theta in degrees: "))
theta = d*pi/180
x = r*cos(theta)
y = r*sin(theta)
print("x =",x," y =",y)

Enter r: 2
Enter theta in degrees: 60
x = 1.0000000000000002  y = 1.7320508075688772


## 'If' statements  

It will happen often in our computer programs that we want to do somethingonly if a certain condition is met: only if n = 0 perhaps, or x > 1/2. We can do this using an if statement. Consider the following example:

In [13]:
x = int(input("Enter a whole number no greater than ten: "))
if x>10:
    print("You entered a number greater than ten.")
    print("Let me fix that for you.")
    x = 10
print("Your number is",x)


Enter a whole number no greater than ten: 5
Your number is 5


In [14]:
x = int(input("Enter a whole number no greater than ten: "))
if x>10:
    print("You entered a number greater than ten.")
    print("Let me fix that for you.")
    x = 10
print("Your number is",x)

Enter a whole number no greater than ten: 11
You entered a number greater than ten.
Let me fix that for you.
Your number is 10


In [17]:
if x==1: #check if x = 1. Note double equals sign
if x>1: #check if x > 1
if x>=1: #check if x ≥ 1
if x<1: #check if x < 1 
if x<=1: #check if x ≤ 1 
if x!=1: #check if x is not equal to 1 

IndentationError: expected an indented block (<ipython-input-17-e8af43dafd0d>, line 2)

You can also combine two conditions in a single if statement, like this:

In [19]:
if x>10 or x<1:
 print("Your number is either too big or too small.")

# you can use "and" in a similar way

if x<=10 and x>=1:
 print("Your number is just right.")

# You can combine more than two criteria on a line as well—as many as you like.
# Two useful further elaborations of the if statement are else and elif:

if x>10:
 print("Your number is greater than ten.")
else:
 print("Your number is fine. Nothing to see here.")

#An even more elaborate example is the following:
if x>10:
 print("Your number is greater than ten.")
elif x>9:
 print("Your number is OK, but you’re cutting it close.")
else:
 print("Your number is fine. Move along.")


Your number is just right.
Your number is fine. Nothing to see here.


The statement elif means “else if”—if the first criterion is not met it tells the computer to try a different one. Notice that we can use both elif and else, as here—if neither of the conditions specified in the if and elif clauses is satisfied then the computer moves on to the else clause

## 'While' Statement

As with the if statement, the while statement checks if the condition given is
met (in this case if x > 10). If it is, it executes the indented block of code
immediately following; if not, it skips the block. However (and this is the
important difference), if the condition is met and the block is executed, the
program then loops back from the end of the block to the beginning and checks
the condition again. If the condition is still true, then the indented lines will be executed again. And it will go on looping around like this, repeatedly checking the condition and executing the indented code, until the condition is finally false. (And if it is never false, then the loop goes on forever.
17)

In [20]:
x = int(input("Enter a whole number no greater than ten: "))
while x>10:
 print("This is greater than ten. Please try again.")
 x = int(input("Enter a whole number no greater than ten: "))
print("Your number is",x)


Enter a whole number no greater than ten: 10
Your number is 10


### Example

In [1]:
#. Suppose we want to calculate the Fibonacci numbers up to 1000
f1,f2 = 1,1
while f1<=1000:
 print(f1)
 f1,f2 = f2,f1+f2

1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987


## Break and continue 

Two useful refinements of the while statement are the break and continue statements.The break statement allows us to break out of a loop even if the condition in the while statement is not met. For instance,

In [21]:
while x>10:
 print("This is greater than ten. Please try again.")
 x = int(input("Enter a whole number no greater than ten: "))
 if x==111:
    break


This loop will continue looping until you enter a number not greater than 10,
except if you enter the number 111, in which case it will give up and proceed with the rest of the program. If the while loop is followed by an else statement, the else statement is not executed after a break.

## Lists  

A list is a list of quantities, one after the other. Quantities can any type that python knows about (strings, floats etc.)

In [2]:
#A variable can set equal to a list.
r = [1, 1, 2, 3, 5, 8, 13, 21]
print(r)

[1, 1, 2, 3, 5, 8, 13, 21]


In [4]:
#The quantities that make up the elements of a list can be specified using other
#variables, like this:
x = 1.0
y = 1.5
z = -2.2
r = [x, y, z]
print(r)

[1.0, 1.5, -2.2]


In [8]:
#The elements of lists can also be calculated from entire mathematical expressions,
#like this:
r = [2*x, x+y, z/sqrt(x**2+y**2)]
print(r)

[2.0, 2.5, -1.2203404316955042]


In [9]:
#The individual elements in a list r are denoted r[0], r[1], r[2], and so forth.
from math import sqrt
r = [ 1.0, 1.5, -2.2 ]
length = sqrt( r[0]**2 + r[1]**2 + r[2]**2 )
print(length)


2.8442925306655784


In [10]:
#We can change the values of individual elements of a list at any time, like 
#this:
r = [ 1.0, 1.5, -2.2 ]
r[1] = 3.5
print(r)

[1.0, 3.5, -2.2]


In [11]:
#A powerful and useful feature of Python is its ability to perform operations
#on entire lists at once.
r = [ 1.0, 1.5, -2.2 ]
total = sum(r)
print(total)

r = [ 1.0, 1.5, -2.2 ]
mean = sum(r)/len(r)
print(mean)

0.2999999999999998
0.09999999999999994


A special, and especially useful, function for lists is the function map, which
is a kind of meta-function—it allows you apply ordinary functions, like log
or sqrt, to all the elements of a list at once. Thus map(log,r) takes the natural logarithm of each element of a list r in turn. More precisely, map creates a 50 specialized object in the computer memory, called an iterator, that contains the logs, one after another in order. Normally we will want to convert this iterator into a new list, which we can do with the built-in function list. 21 Thus, consider this snippet of code:

In [12]:
from math import log
r = [ 1.0, 1.5, 2.2 ]
logr = list(map(log,r))
print(logr)


[0.0, 0.4054651081081644, 0.7884573603642703]


In [14]:
#Another feature of lists in Python, one that we will use often, is the ability
#to add elements to an already existing list. 
r = [ 1.0, 1.5, 2.2 ]
r.append(6.1)
print(r)

r = [ 1.0, 1.5, 2.2 ]
x = 0.8
r.append(2*x+1)
print(r)


[1.0, 1.5, 2.2, 6.1]
[1.0, 1.5, -2.2, 2.6]


In [16]:
#Creating empty list

r = []
print(r)
r.append(1.0)
r.append(1.5)
r.append(-2.2)
print(r)


[]
[1.0, 1.5, -2.2]


In [17]:
#We can also remove a value from the end of a list by saying r.pop():
r = [ 1.0, 1.5, -2.2, 2.6 ]
r.pop()
print(r)


[1.0, 1.5, -2.2]


## Arrays

1. The number of elements in an array is fixed. You cannot add elements to
   an array once it is created, or remove them.
2. The elements of an array must all be of the same type, such as all floats or
   all integers. You cannot mix elements of different types in the same array
   and you cannot change the type of the elements once an array is created.
3. Arrays can be two-dimensional, like matrices in algebra. That is, rather
   than just a one-dimensional row of elements, we can have a grid of them.
   Indeed, arrays can in principle have any number of dimensions, including
   three or more, although we won’t use dimensions above two in this
   book. Lists, by contrast, are always just one-dimensional.
4. Arrays behave roughly like vectors or matrices: you can do arithmetic
   with them, such as adding them together, and you will get the result you
   expect. This is not true with lists. If you try to do arithmetic with a list
   you will either get an error message, or you will not get the result you
   expect.
5. Arrays work faster than lists. Especially if you have a very large array
   with many elements then calculations may be significantly faster using
   an array

In [19]:
#One dimesnional array 
from numpy import zeros
a = zeros(4,float)
print(a)


[ 0.  0.  0.  0.]


Note that arrays are printed out slightly differently from lists—there are no
commas between the elements, only spaces.


In [20]:
#To create a two-dimensional floating-point array with m rows and n columns,
#you say “zeros([m,n],float)”, so

a = zeros([3,4],float)
print(a)


[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [21]:
from numpy import empty
a = empty(4,float)
print(a)

[ 0.  0.  0.  0.]


In [24]:
#A different way to create an array is to take a list and convert it into an
#array, which you can do with the function array from the package numpy. 
from numpy import array
r = [ 1.0, 1.5, -2.2 ]
a = array(r,float)
print(a)


[ 1.   1.5 -2.2]


In [25]:
#We can also create two-dimensional arrays with specified initial values
a = array([[1,2,3],[4,5,6]],int)
print(a)


[[1 2 3]
 [4 5 6]]


In [27]:
#We can also set individual elements equal to new values
#thus:
r = [ 1.0, 1.5, -2.2 ]
a = array(r,float)
a[2] = 4
print(a)
#Note, as with lists, that the numbering of the elements starts at zero, not one.

[ 1.   1.5  4. ]


In [28]:
#For two-dimensional arrays we use two indices, separated by commas, to
#denote the individual elements, as in a[2,4], with counting again starting at
#zero, for both indices. Thus, for example

from numpy import zeros
a = zeros([2,2],int)
a[0,1] = 1
a[1,0] = -1
print(a)


[[ 0  1]
 [-1  0]]


## READING AN ARRAY FROM A FILE


Suppose we have a text file that contains the following stringof numbers, on consecutive lines:

1.0 

1.5

-2.2

2.6

and suppose that this file is called values.txt on the computer. Then we can
do the following:

In [31]:
from numpy import loadtxt
a = loadtxt("values.txt",float)
print(a)

[ 1.   1.5 -2.2  2.6]


You can also read a two dimensional grid of values if they are put into the file in a two-dimensional array.

## Arithmetic with arrays

As with lists, the individual elements of an array behave like ordinary variables, and we can do arithmetic with them in the usual way. We can write
things like

In [32]:
a[0] = a[1] + 1
#or
x = a[2]**2 - 2*a[3]/y
print(a)
print(x)

[ 2.5  1.5 -2.2  2.6]
1.37333333333


In [33]:
#In general, when doing arithmetic with entire arrays, the rule is that whatever 
#arithmetic operation you specify is done independently to each element of the
#array or arrays involved.Consider this short program:
from numpy import array
a = array([1,2,3,4],int)
b = 2*a
print(b)

[2 4 6 8]


In [34]:
#If you add or subtract two arrays, the computer will add or subtract each
#element separately, so that
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(a+b)

[ 3  6  9 12]


In [35]:
#You can also add a scalar quantity to an array (or subtractone), 
#which the computer interprets to mean it should add that quantity to
#every element. So
a = array([1,2,3,4],int)
print(a+1)

[2 3 4 5]


In [36]:
#if we multiply two arrays together the outcome is perhaps not
#exactly what you would expect—you do not get the vector (dot) product of the
#two. If we do this:
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(a*b)

[ 2  8 18 32]


In [38]:
# more often in physics calculations we want the true vector
#dot product of our arrays. This can be calculated using the function dot from
#the package numpy:
from numpy import array,dot
a = array([1,2,3,4],int)
b = array([2,4,6,8],int)
print(dot(a,b))

60


In [39]:
a = array([[1,3],[2,4]],int)
b = array([[4,-2],[-3,1]],int)
c = array([[1,2],[2,1]],int)
print(dot(a,b)+2*c)

[[-3  5]
 [ 0  2]]


In [44]:
a = array([[1,2,3],[4,5,6]],int)
print(a.size) # how many elements in an array
print(a.shape) # shape of the array (in this case a 2x3 matrix)


6
(2, 3)


In [47]:
# Warning, "a = b" just declares a to be renamed b not values of a copied into b 
#i.e.
from numpy import array
a = array([1,1],int)
b = a
a[0] = 2
print(a)
print(b)



[2 1]
[2 1]


In [52]:
#to actually copy 
from numpy import copy
a = array([1,1],int)
b = copy(a)
a[0] = 2
print(a)
print(b)

[2 1]
[1 1]


## Slicing (lists and arrays)

Suppose we have a list r. Then r[m:n] is another list composed of a
subset of the elements of r, starting with element m and going up to but not
including element n. Here’s an example:


In [54]:
r = [ 1, 3, 5, 7, 9, 11, 13, 15 ]
s = r[2:5] #slicing elements 2 to 5 from list r
print(s)

[5, 7, 9]


In [55]:
from numpy import array
a = array([2,4,6,8,10,12,14,16],int)
b = a[3:6] #slicing elements 3 to 6 from array a 
print(b)


[ 8 10 12]


In [56]:
from numpy import array
a = array([2,4,6,8,10,12,14,16],int)
b = a[3:] #slicing elements 3 to end from array a (works in lists and can be [:3])
          # to do the oppoisite
print(b)


[ 8 10 12 14 16]


## for loops

A for loop is a loop
that runs through the elements of a list or array in turn.

In [57]:
r = [ 1, 3, 5 ]
for n in r:
 print(n)
 print(2*n)
print("Finished")

1
2
3
6
5
10
Finished


 The most common use of the for loop is simply to run through a given piece
of code a specified number of times, such as ten, say, or a million. To achieve
this, Python provides a special built-in function called range, which creates a
list of a given length, usually for use with a for loop. 

In [61]:
print(range(5)) #a list of consecutive integers, starting at 0 going up to but not
         #including 5. (5 elements but not 5 itself)

range(0, 5)


In [69]:
r = range(5)
for n in r:
 print("Hello again")

for n in range(5):
 print(n**2)


Hello again
Hello again
Hello again
Hello again
Hello again
0
1
4
9
16


In this case we are not actually interested in the values r contains, only the fact that there are five of them—they merely provide a convenient tool that allows us to run around the same piece of code a given number of times

In [71]:
#there are a number of useful variants of the range function, as follows:

range(5) # [0, 1, 2, 3, 4] 
range(2,8) # [2, 3, 4, 5, 6, 7] note how it doesnt include 8 
range(2,20,3) # [2, 5, 8, 11, 14, 17] format is: [Start, finish, step]
range(20,2,-3) # [20, 17, 14, 11, 8, 5]

range(20, 2, -3)

In [72]:
#Thus, for example, we can print out the first ten powers of two with the
#following lines:
for n in range(1,11):
 print(2**n)


2
4
8
16
32
64
128
256
512
1024


Range function has to be integers and will not work with non integer arguments 
like floats 

In [73]:
p = 10
q = 2
for n in range(p/q):
 print(n)


TypeError: 'float' object cannot be interpreted as an integer

In [74]:
for n in range(p//q): # // for integer divsion 
 print(n)

0
1
2
3
4


### Example

emission lines in the spectrum of hydrogen (2.7 in book check for clarity)

In [76]:
R = 1.097e-2
for m in range(1,4): # takes the integer variable m through values 1,2,3 
 print("Series for m =",m)
 for n in range(m+1,m+6): # for each value of m the second loop takes k through 
                          # values 1, 2 ,3 4 ,5, adds those values to m to 
                          # calulate n and then applies the Rydberg formular
     invlambda = R*(1/m**2-1/n**2) # Rydberg formular
     print(" ",1/invlambda," nm")

Series for m = 1
  121.5436037678517  nm
  102.55241567912488  nm
  97.23488301428137  nm
  94.95594044363415  nm
  93.76220862091418  nm
Series for m = 2
  656.3354603463993  nm
  486.1744150714068  nm
  434.084299170899  nm
  410.2096627164995  nm
  397.04243897498225  nm
Series for m = 3
  1875.2441724182836  nm
  1281.9051959890612  nm
  1093.8924339106654  nm
  1005.013673655424  nm
  954.6697605038536  nm
